[package]
name = "your-app-name"
version = "1.0.0"

[web]
  # the entrypoint of your PHP app
  entrypoint = "public/index.php"  # or just "index.php" depending on your folder structure
  # any public files like css/js/images
  assets = ["css", "js", "uploads"]

# this is where rewrites happen
[[web.routes]]
pattern = "/post/:slug"
destination = "/post/index.php?slug=:slug"

[[web.routes]]
pattern = "/search/:query"
destination = "/search.php?q=:query"

[[web.routes]]
pattern = "/category/:id"
destination = "/category.php?id=:id"

[[web.routes]]
pattern = "/about"
destination = "/about.php"

[[web.routes]]
pattern = "/index"
destination = "/index.php"
